language: java
os:
  - linux
  - osx
services:
  - docker
jdk:
  - oraclejdk8
install:
  - ./gradlew assemble --stacktrace --info
script:
  - ./gradlew check integrationTest --stacktrace --info
after_success:
  - bash <(curl -s https://codecov.io/bash)