language: java
services:
  - docker
jdk:
  - oraclejdk8
before_script:
  - chmod +x gradlew
script:
  - ./gradlew check integrationTest --stacktrace --info
after_success:
  - bash <(curl -s https://codecov.io/bash)